name: binder-environment
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - matplotlib>=1.5
  - numpy>=1.11
  - pandas
  - python-dateutil
  - scipy
  - scikit-image
  - pytest
  - plotnine
  - opencv-python<4
